# This is the global configuration file of name matching solution
# platform, IO setup
platform: aws
file_store: localfs
# local fs volume location
localfs_volume_loc: localfs
# bucket_name is initiated later in load function
bucket_name: dummy
region: eu-west-1
api_store: pg
filestore_put_object_url_ttl: 1800
filestore_get_object_url_ttl: 1800
# actually we don't need executor. Revisit it later, maybe delete it
#executor: CeleryExecutor
executor: LocalExecutor
app_log_group: "/dummy"

kubernetes:
  in_cluster: True
  tcp_keep_idle: 120
  tcp_keep_intvl: 30
  tcp_keep_cnt: 6
  cluster_context:
  config_file:
  enable_tcp_keepalive: True
  verify_ssl: True
