---
apiVersion: v1
kind: Pod
metadata:
  namespace: nm
  name: nm-pod
  labels:
    app: nm-pod-placeholder  
spec:
  containers:
    - name: base
      image: perl
      resources:
        requests:
          memory: "200Mi"
          cpu: 0.25
        limits:
          memory: "264Mi"
          cpu: 0.25      
      command: ["/bin/bash"]
      args: ["-c", 'echo {\"hello\" : \"world\"} | cat > /tmp/return.json']
      volumeMounts:
        - mountPath: /app/localfs
          name: nm-dataset-volume
  restartPolicy: Never
  volumes:
    - name: nm-dataset-volume
      persistentVolumeClaim:
        claimName: 'nm-dataset-claim'
  # https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-terminating-with-grace
  # worker will change nm task status during grace termination period
  terminationGracePeriodSeconds: 10